version: '3.8'
services:
  app:
    container_name: foodmarket_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/foodmarketdb
  db:
    container_name: foodmarket_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foodmarketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
